In [ ]:
import numpy as np 
import pandas as pd

#nombre des clients
n = 9

#capacité du vehicule
Q = 20

#list des clients
N = [i for i in range(1,n+1)]

#nombre des villes (ou nombre des vertices)
V=[0]+N

#matrice coûts
C = np.asarray([[0, 217, 690, 581, 749, 894, 1063, 938, 1065, 1000],
 [217, 0, 462, 409, 537, 677, 845, 711, 838, 773],
 [690, 462, 0, 254, 137, 537, 450, 251, 378, 313],   
 [581, 409, 254, 0, 215, 706, 698, 499, 626, 561],
 [749, 537, 137, 215, 0, 646, 559, 359, 487, 421],
 [894, 677, 537, 706, 646, 0, 206, 290, 469, 403],   
 [1063, 845, 450, 698, 559, 206, 0, 203, 382,317],   
 [938, 711, 251, 499, 359, 290, 203, 0, 187, 122],   
 [1065, 838, 378, 626, 487, 469, 382, 187, 0, 66],
 [1000, 773, 313, 561, 421, 403, 317, 122, 66, 0],   
])

#liste des demandes associée aux solutions [1,2,3,4,5,6,7,8,9]
q=[2,5,5,5,5,5,5,5,10]

l=[]
for w in range(20,50,10):
    for t0 in range(10,200,20):
        for nb_iter_cycle in range(1,10,3):
            for a in np.arange(0.1,0.5,0.2):
                for nb_camions in range(1,3):
                    s0=[1, 2, 4, 3, 7, 8, 9, 5, 6]
                    for k in range(1,nb_camions):
                        s0.append(0)
                    rd.shuffle(s0)
                    s0 = [0]+s0+[0]
                    print(w,t0,nb_iter_cycle,a,nb_camions)
                    l.append(rs(s0,w,t0,nb_iter_cycle,a)+(w,t0,nb_iter_cycle,a,nb_camions))data = data.drop([1157])
data = data.drop([1156])
data = data.drop([1155])

In [ ]:
import random as rd

def N(s):
    n=len(s)
    i=rd.randint(1,n-2)
    j=rd.randint(1,n-2)
    while(i==j):
        j=rd.randint(1,n-2)
    x=s[i]
    s[i]=s[j]
    s[j]=x
    return s

In [ ]:
w=500

def f(x,w):
    s=0
    for i in range(len(x)-1):
        s+=C[x[i]][x[i+1]]
    return w*len(x)+s

In [ ]:
t0=100
nb_iter_cycle=2
a=0.5

from math import exp

def rs(s,w,t0=100,nb_iter_cycle=2,a=0.5):
    s_et=s
    nb_iter=0
    nv_cycle = True
    t=t0
    while(nv_cycle):
        nb_iter=0
        nv_cycle=False
        while(nb_iter<nb_iter_cycle and t!=0):
            nb_iter+=1
            s1=N(s)
            df=f(s1,w)-f(s,w)
            if(df<0):
                s=s1
                nv_cycle=True
            else:
                prob=exp(-df/t)
                q=rd.random()
                if(q<prob):
                    s=s1
                    nv_cycle=True
            if(f(s,w)<f(s_et,w)):
                s_et=s
        t*=a
    return s,f(s,w)

In [ ]:
l=[]
for w in range(20,50,10):
    for t0 in range(10,200,20):
        for nb_iter_cycle in range(1,10,3):
            for a in np.arange(0.1,0.5,0.2):
                for nb_camions in range(1,3):
                    s0=[1, 2, 4, 3, 7, 8, 9, 5, 6]
                    for k in range(1,nb_camions):
                        s0.append(0)
                    rd.shuffle(s0)
                    s0 = [0]+s0+[0]
                    print(w,t0,nb_iter_cycle,a,nb_camions)
                    l.append(rs(s0,w,t0,nb_iter_cycle,a)+(w,t0,nb_iter_cycle,a,nb_camions))

In [ ]:
def fusion(t1,t2):
   if t1==[]:
      return t2
   elif t2==[]:
      return t1
   else:
      if t1[0][1]<t2[0][1]:
         return [t1[0]] + fusion(t1[1:],t2)
      else:
         return [t2[0]] + fusion(t1,t2[1:])

def tri_fusion(T):
   if len(T)<=1:
      return T
   else:
      c = len(T)//2
   return fusion(tri_fusion(T[0:c]),tri_fusion(T[c:]))

tri_fusion(l)

In [ ]:
w=100
t0=100
nb_iter_cycle =2
(array([[ 651, 1096,  623, ...,  500,  744,  927],
        [ 632,  740,   88, ...,  758,  494, 1124],
        [ 276,  310,  495, ...,  221,  513,  981],
        ...,
        [ 704,  741,  255, ...,  782,  771, 1100],
        [ 118,  346,  837, ...,  760,  903,  396],
        [ 108,  404, 1125, ..., 1010,  509,  200]]),
 4286943.417282038)

w=100
t0=150
nb_iter_cycle =2
(array([[ 382,  566,  181, ...,  415,  530,  650],
        [1066,  274,  569, ...,  603,  790,  550],
        [ 964,  933,  324, ...,  259,  827,  942],
        ...,
        [ 618,  639, 1054, ...,  176,  730,  343],
        [  56,  852, 1110, ..., 1077,  808,  972],
        [ 605,  608,  582, ...,  737,  680,  373]]),
 4287254.053457645)

w=300
t0=100
nb_iter_cycle =2
(array([[ 607,   69,  914, ...,  808,  519,  209],
        [ 473,  732,  218, ...,  113,  556,  522],
        [ 475,  661,  833, ...,  802, 1089,   71],
        ...,
        [ 794,  438, 1075, ...,  560,  184,  328],
        [ 886,  820,  743, ...,  842,   62,  415],
        [1080, 1073,  529, ...,  952,  183, 1096]]),
 4289863.990014517)

idem mais avec 89 camions
(array([[  39,  771, 1145, ..., 1070,  140,  135],
        [ 265,  313,  861, ...,  487,  962,  385],
        [ 117, 1140,  318, ...,  654,  752,  506],
        ...,
        [ 982,  552,  725, ...,  488,  424,  836],
        [1073,  451,  108, ..., 1081,    0,  275],
        [ 703,  867,   41, ...,  753,    6, 1096]]),
 4027735.3427197267)

w=500
nb_iter_cycle =3
89 camions
(array([[ 533,  718,  927, ...,  579,  204,   99],
        [1138,  277,  355, ...,  290,  365,   10],
        [1122,  329,  949, ...,  320,   49, 1109],
        ...,
        [ 436,   67,  250, ..., 1148,  809,   79],
        [ 346,  641,  551, ..., 1033, 1053,  679],
        [ 945, 1003,  692, ...,  625,  750,    6]]),
 4045115.7005335554)

idem mais 34 camions et nb_iter_cycle =2
(array([[ 430,  561,  987, ...,  396,  283,  885],
        [ 511,  322, 1073, ...,  465,  612,  584],
        [ 683,  719,  348, ..., 1104,  790,  677],
        ...,
        [ 429,  442,  188, ...,  118,  196, 1039],
        [ 888, 1090,  880, ...,  860, 1122,  709],
        [ 871,   63,  939, ...,  813,  794,  634]]),
 4220010.40940688)

idem mais 68 camions
(array([[ 504,  167,  405, ...,  617,  862,  243],
        [  30,  342,  332, ...,  347,  622,  153],
        [ 671, 1140,  908, ...,  161,  747, 1033],
        ...,
        [ 718,   23,  241, ...,  911,  224,   40],
        [ 151,  321,  444, ...,  578,  276,  995],
        [ 216, 1044, 1072, ..., 1142,  727,  436]]),
 4109740.8552210727)

idem mais 17 camions
(array([[ 381,  769,  941, ...,  801,  830,  450],
        [ 997,  915, 1115, ...,  921,  606,  165],
        [ 436,  631,  855, ..., 1047, 1009,  162],
        ...,
        [ 742, 1091,  134, ...,  958,  396,  963],
        [  89,  671,  174, ...,  782,  476,  914],
        [1034,   10,  938, ...,  274,   98,  679]]),
 4275432.176013547)

idem mais avec 105 camions
(array([[  28,  756, 1061, ...,  564,    1,   66],
        [ 765,  476,  239, ...,  699,   45,  439],
        [ 446, 1138,  853, ...,  841, 1019,  189],
        ...,
        [ 631,  829,  807, ...,  645,  850,  995],
        [ 808, 1110,  809, ...,  689,  137,  999],
        [  98,   74,  610, ...,  499,  203,  654]]),
 3985715.5096236463)


In [ ]:
import time

a = time.time()
for i in range(100000000):
    x=0
b=time.time()
print(b-a)


In [ ]:
centrale :
1e8 : 3.76
1e9 : 34.6
    
kaggle :
1e8 : 5.0089
1e9 : 52.05
    

In [ ]:
for i in range(10,150):
    print(1156/i)